"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/navbar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [theme, setTheme] = useState("dark");

  return (
    <html lang="en" className={theme}>
      <body className="bg-bgLight dark:bg-bgDark">
        <Navbar setTheme={setTheme} theme={theme} />
        {children}
      </body>
    </html>
    // <html lang="en">
    //   <body className={inter.className}>

    //   </body>
    // </html>
  );
}
